[package]
edition = "2021"
license = "GPLv3"
name = "app-promotion-rpc"
version = "0.1.0"

[dependencies]
pallet-evm = { workspace = true }
parity-scale-codec = { workspace = true }
sp-api = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }

[features]
default = []
std = ["pallet-evm/std", "parity-scale-codec/std", "sp-api/std", "sp-runtime/std", "sp-std/std"]
