version: "3.5"

services:
  node_einstein:
    image: nft-parachain
    ports:
      - 9935:9935
    build:
      context: ./
      dockerfile: Dockerfile-testnet
    volumes:
      - ./chain-data-einstein:/chain-data
    networks: 
      - substrate_network
    restart: always
    environment:
      - NODE=einstein
      - P2PPORT=30335
      - WSPORT=9945
      - RPCPORT=9935
      - BOOTNODE=True
      - VALIDATOR=True

  node_newton:
    image: nft-parachain
    ports:
      - 9936:9936
    build:
      context: ./
      dockerfile: Dockerfile-testnet
    volumes:
      - ./chain-data-newton:/chain-data
    networks: 
      - substrate_network
    restart: always
    environment:
      - NODE=newton
      - P2PPORT=30336
      - WSPORT=9946
      - RPCPORT=9936
      - BOOTNODE=False
      - BOOTPORT=30335
      - BOOTID=12D3KooWRLrjXxByPkSCzcsRyf6652brnJT9s4AQHR3uujJ35mxz
      - VALIDATOR=True

  node_bohr:
    image: nft-parachain
    ports:
      - 9944:9944
    build:
      context: ./
      dockerfile: Dockerfile-testnet
    volumes:
      - ./chain-data-bohr:/chain-data
    networks: 
      - substrate_network
    restart: always
    environment:
      - NODE=bohr
      - P2PPORT=30334
      - WSPORT=9944
      - RPCPORT=9934
      - BOOTNODE=False
      - BOOTPORT=30335
      - BOOTID=12D3KooWRLrjXxByPkSCzcsRyf6652brnJT9s4AQHR3uujJ35mxz
      - VALIDATOR=False
      
networks: 
  substrate_network:
    driver: bridge
    name: substrate_network
