[package]
name = "pallet-refungible"
version = "0.2.2"
license = "GPLv3"
edition = "2021"

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.1.2'

[dependencies]
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.25" }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "unique-polkadot-v0.9.25" }
evm-coder = { default-features = false, path = '../../crates/evm-coder' }
pallet-evm-coder-substrate = { default-features = false, path = '../../pallets/evm-coder-substrate' }
pallet-common = { default-features = false, path = '../common' }
pallet-structure = { default-features = false, path = '../structure' }
struct-versioning = { path = "../../crates/struct-versioning" }
up-data-structs = { default-features = false, path = '../../primitives/data-structs' }
ethereum = { version = "0.12.0", default-features = false }
scale-info = { version = "2.0.1", default-features = false, features = ["derive",] }
derivative = { version = "2.2.0", features = ["use_core"] }

[features]
default = ["std"]
std = [
    "ethereum/std",
    "evm-coder/std",
    'frame-benchmarking/std',
    "frame-support/std",
    "frame-system/std",
    "pallet-common/std",
    "pallet-evm/std",
    "pallet-evm-coder-substrate/std",
    "pallet-structure/std",
    "sp-runtime/std",
    "sp-std/std",
    "up-data-structs/std",
]
runtime-benchmarks = [
    'frame-benchmarking',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
    'up-data-structs/runtime-benchmarks',
]
