[package]
authors = ['Unique Network <support@uniquenetwork.io>']
description = 'Unique Runtime Common'
edition = '2021'
homepage = 'https://unique.network'
license = 'All Rights Reserved'
name = 'unique-runtime-common'
repository = 'https://github.com/UniqueNetwork/unique-chain'
version = '0.9.24'

[features]
default = ['std']
std = [
    'sp-core/std',
    'sp-std/std',
    'sp-runtime/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-consensus-aura/std',
    'pallet-common/std',
    'pallet-unique/std',
    'pallet-fungible/std',
    'pallet-nonfungible/std',
    'pallet-refungible/std',
    'up-data-structs/std',
    'pallet-evm/std',
    'fp-rpc/std',
]
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks',
]

opal-runtime = []
quartz-runtime = []
unique-runtime = []

refungible = []

[dependencies.sp-core]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.24"

[dependencies.sp-std]
default-features = false
git = 'https://github.com/paritytech/substrate'
branch = 'polkadot-v0.9.24'

[dependencies.sp-runtime]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.24"

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.1.2'

[dependencies.scale-info]
default-features = false
features = ["derive"]
version = "2.0.1"

[dependencies.frame-support]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.24"

[dependencies.frame-system]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.24"

[dependencies.pallet-common]
default-features = false
path = "../../pallets/common"

[dependencies.pallet-unique]
default-features = false
path = "../../pallets/unique"

[dependencies.pallet-fungible]
default-features = false
path = "../../pallets/fungible"

[dependencies.pallet-nonfungible]
default-features = false
path = "../../pallets/nonfungible"

[dependencies.pallet-refungible]
default-features = false
path = "../../pallets/refungible"

[dependencies.pallet-unique-scheduler]
default-features = false
path = "../../pallets/scheduler"

[dependencies.up-data-structs]
default-features = false
path = "../../primitives/data-structs"

[dependencies.sp-consensus-aura]
default-features = false
git = "https://github.com/paritytech/substrate"
branch = "polkadot-v0.9.24"

[dependencies.fp-rpc]
default-features = false
git = "https://github.com/uniquenetwork/frontier"
branch = "unique-polkadot-v0.9.24"

[dependencies]
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", branch = "unique-polkadot-v0.9.24" }
evm-coder = { default-features = false, path = '../../crates/evm-coder' }
up-sponsorship = { default-features = false, git = "https://github.com/UniqueNetwork/pallet-sponsoring", branch = 'polkadot-v0.9.24' }

rmrk-rpc = { default-features = false, path = "../../primitives/rmrk-rpc" }
