[package]
authors = ['Unique Network <support@uniquenetwork.io>']
description = 'Unique Runtime Common'
edition = '2021'
homepage = 'https://unique.network'
license = 'All Rights Reserved'
name = 'unique-runtime-common'
repository = 'https://github.com/UniqueNetwork/unique-chain'
version = '0.1.0'

[features]
default = ['std']
std = [
    'sp-core/std',
    'sp-runtime/std',
    'codec/std',
    'frame-support/std',
    'frame-system/std',
    'sp-consensus-aura/std',
    'pallet-common/std',
    'fp-rpc/std',
]
runtime-benchmarks = [
    'sp-runtime/runtime-benchmarks',
    'frame-support/runtime-benchmarks',
    'frame-system/runtime-benchmarks'
]

[dependencies.sp-core]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.17'

[dependencies.sp-runtime]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.17'

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '2.3.0'

[dependencies.scale-info]
default-features = false
features = ["derive"]
version = "1.0.0"

[dependencies.frame-support]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.17'

[dependencies.frame-system]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.17'

[dependencies.pallet-common]
default-features = false
path = "../../pallets/common"

[dependencies.sp-consensus-aura]
default-features = false
git = 'https://github.com/paritytech/substrate.git'
branch = 'polkadot-v0.9.17'

[dependencies.fp-rpc]
default-features = false
git = "https://github.com/uniquenetwork/frontier.git"
branch = "unique-polkadot-v0.9.17"
