[package]
edition = "2021"
license = "GPLv3"
name = "up-rpc"
version = "0.1.3"

[dependencies]
codec = { workspace = true }
pallet-common = { workspace = true }
pallet-evm = { workspace = true }
sp-api = { workspace = true }
sp-core = { workspace = true }
sp-runtime = { workspace = true }
sp-std = { workspace = true }
up-data-structs = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pallet-common/std",
	"sp-api/std",
	"sp-core/std",
	"sp-runtime/std",
	"sp-std/std",
	"up-data-structs/std",
]
