[package]
authors = ['Unique Network <support@uniquenetwork.io>']
description = 'Unique Runtime Common Primitives'
edition = '2021'
homepage = 'https://unique.network'
license = 'All Rights Reserved'
name = 'up-common'
repository = 'https://github.com/UniqueNetwork/unique-chain'
version.workspace = true

[features]
default = ['std']
std = [
	'cumulus-primitives-core/std',
	'fp-rpc/std',
	'frame-support/std',
	'pallet-evm/std',
	'sp-consensus-aura/std',
	'sp-core/std',
	'sp-runtime/std',
	'sp-std/std',
]

[dependencies]
cumulus-primitives-core = { default-features = false, git = "https://github.com/paritytech/cumulus", branch = "polkadot-v0.9.37" }
fp-rpc = { default-features = false, git = "https://github.com/uniquenetwork/unique-frontier", branch = "unique-polkadot-v0.9.37" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/unique-frontier", branch = "unique-polkadot-v0.9.37" }
sp-consensus-aura = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-runtime = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.37" }
