[package]
name = "nft_transfer"
version = "0.1.0"
authors = ["[Greg Zaitsev] <[your_email]>"]
edition = "2018"

[workspace]

[dependencies]
ink_primitives = { default-features = false }
ink_metadata = { default-features = false, features = ["derive"], optional = true }
ink_env = { default-features = false }
ink_storage = { default-features = false }
ink_lang = { default-features = false }

scale = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
scale-info = { version = "0.6.0", default-features = false, features = ["derive"] }

[lib]
name = "nft_transfer"
path = "lib.rs"
crate-type = [
	# Used for normal contract Wasm blobs.
	"cdylib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
