[package]
name = "pallet-evm-coder-substrate"
version = "0.1.3"
license = "GPLv3"
edition = "2021"

[dependencies]
scale-info = { version = "2.0.1", default-features = false, features = [
    "derive",
] }
sp-std = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
sp-core = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
ethereum = { version = "0.12.0", default-features = false }
evm-coder = { default-features = false, path = "../../crates/evm-coder" }
pallet-ethereum = { default-features = false, git = "https://github.com/uniquenetwork/frontier", rev = "89a37c5a489f426cc7a42d7b94019974093a052d" }
pallet-evm = { default-features = false, git = "https://github.com/uniquenetwork/frontier", rev = "89a37c5a489f426cc7a42d7b94019974093a052d" }
frame-support = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
frame-system = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
frame-benchmarking = { default-features = false, optional = true, git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.27" }
up-data-structs = { default-features = false, path = "../../primitives/data-structs" }

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '3.1.2'

[features]
default = ["std"]
std = [
    "sp-std/std",
    "sp-core/std",
    "ethereum/std",
    "evm-coder/std",
    "pallet-ethereum/std",
    "pallet-evm/std",
    "frame-support/std",
    "frame-system/std",
    'frame-benchmarking/std',
]
runtime-benchmarks = ['frame-benchmarking']
